#!/usr/bin/python3

import html
import os

print("Status: 200 OK")
print("Content-Type: text/html\r\n")
print("<!doctype html>")
print("<html lang=\"en\">")
print("<head><meta charset=\"utf-8\"><title>Python CGI Bonus</title></head>")
print("<body>")
print("<h1>Python CGI works</h1>")
print("<p>This response was generated by <code>bonus_python.py</code>.</p>")
print("<dl>")
print("<dt>REQUEST_METHOD</dt><dd>%s</dd>" % html.escape(os.environ.get("REQUEST_METHOD", "")))
print("<dt>QUERY_STRING</dt><dd>%s</dd>" % html.escape(os.environ.get("QUERY_STRING", "")))
print("<dt>REQUEST_URI</dt><dd>%s</dd>" % html.escape(os.environ.get("REQUEST_URI", "")))
print("</dl>")
print("<p><a href=\"/bonus.html\">Back to bonus demo</a></p>")
print("</body>")
print("</html>")
