#!/bin/bash

printf 'Status: 200 OK\r\n'
printf 'Content-Type: text/html\r\n\r\n'
printf '<!doctype html>\n'
printf '<html lang="en">\n'
printf '<head><meta charset="utf-8"><title>Shell CGI Bonus</title></head>\n'
printf '<body>\n'
printf '<h1>Shell CGI works</h1>\n'
printf '<p>This response was generated by <code>bonus_shell.sh</code>.</p>\n'
printf '<dl>\n'
printf '<dt>REQUEST_METHOD</dt><dd>%s</dd>\n' "$REQUEST_METHOD"
printf '<dt>QUERY_STRING</dt><dd>%s</dd>\n' "$QUERY_STRING"
printf '<dt>SHELL</dt><dd>%s</dd>\n' "$SHELL"
printf '</dl>\n'
printf '<p><a href="/bonus.html">Back to bonus demo</a></p>\n'
printf '</body>\n'
printf '</html>\n'
